/**:
  ros__parameters:
    node_params:
      update_rate_hz: 10.0
    core_params:
      moving_average_num: 1
      threshold_pointcloud_z_high: 1.0
      threshold_pointcloud_z_low: 0.6
      threshold_relative_velocity: 10.0
      threshold_absolute_velocity: 20.0
